version: '2'

services:
  app:
    build:
      context: .
      args:
        APP_NAME: $APP_NAME

  prod:
    extends:
      service: app
    build:
      args:
        ENV: production
    image: $APP_NAME:prod

  dev:
    extends:
      service: app
    build:
      args:
        ENV: development
    image: $APP_NAME:dev
