version: 2

jobs:
  properly_tagged_release:
    machine:
      enabled: true
    working_directory: ~/app
    environment:
      APP_NAME: pgweb
    steps:
      - checkout
      - run:
          name: Build
          when: on_success
          command: docker-compose -f docker-build.yml build prod
      - run:
          name: Authenitcate Docker Hub
          when: on_success
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - deploy:
          name: Tag and Push to Docker Hub
          when: on_success
          command: |
            docker tag ${APP_NAME}:prod ${DOCKER_USER}/${APP_NAME}:${CIRCLE_TAG}
            docker push ${DOCKER_USER}/${APP_NAME}:${CIRCLE_TAG}
  dev_branch:
    machine:
      enabled: true
    working_directory: ~/app
    environment:
      APP_NAME: keycloak
    steps:
      - checkout
      - run:
          name: Build
          when: on_success
          command: docker-compose -f docker-build.yml build prod
      - run:
          name: Authenitcate Docker Hub
          when: on_success
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - deploy:
          name: Tag and Push to Docker Hub
          when: on_success
          command: |
            docker tag ${APP_NAME}:prod ${DOCKER_USER}/${APP_NAME}:dev
            docker push ${DOCKER_USER}/${APP_NAME}:dev

workflows:
  version: 2

  build_and_push_image:
    jobs:
      - properly_tagged_release:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-rc[0-9]+)?$/
            branches:
              ignore: /.*/
      - dev_branch:
          filters:
            branches:
              only: develop
